version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/spring-web-flux/revisions
hooks:
  BeforeInstall:
    - location: spring-webflux-reactive/scripts/stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: spring-webflux-reactive/scripts/deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: spring-webflux-reactive/scripts/start.sh
      timeout: 300
      runas: ec2-user
      
